M48
; DRILL file {KiCad 7.0.8} date Tue Oct 10 13:31:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-10T13:31:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X2.3Y-2.6
X2.5Y-2.5
X2.6Y-2.2
X2.6Y-2.5
X2.6Y-2.7
X2.8Y-2.0
X2.984Y-2.233
X3.0Y-2.0
X3.0Y-2.4
X3.0Y-2.5
T2
X2.7Y-1.9
X2.7984Y-1.9
T0
M30
